FROM golang

ARG T_CONSUMER_KEY
ARG T_CONSUMER_SECRET
ARG T_ACCESS_TOKEN
ARG T_ACCESS_SECRET
ARG GCLOUD_PROJECT
ARG GCLOUD_INSTANCE
ARG GCLOUD_DB
ARG GOOGLE_APPLICATION_CREDENTIALS

ENV T_CONSUMER_KEY=${T_CONSUMER_KEY}
ENV T_CONSUMER_SECRET=${T_CONSUMER_SECRET}
ENV T_ACCESS_TOKEN=${T_ACCESS_TOKEN}
ENV T_ACCESS_SECRET=${T_ACCESS_SECRET}
ENV GCLOUD_PROJECT=${GCLOUD_PROJECT}
ENV GCLOUD_INSTANCE=${GCLOUD_INSTANCE}
ENV GCLOUD_DB=${GCLOUD_DB}
ENV GOOGLE_APPLICATION_CREDENTIALS=${GOOGLE_APPLICATION_CREDENTIALS}

COPY ./ /go/src/github.com/mchmarny/tfeel-trader
WORKDIR /go/src/github.com/mchmarny/tfeel-trader

RUN go get ./
RUN go build

CMD ./tfeel-trader --refresh=25
